openapi: 3.1.0
info:
  title: Scribe-Server API
  version: 0.0.0
paths:
  /latest:
    get:
      operationId: getLatestUpdateTime
      responses:
        "200":
          description: Returns the datetime of the latest Scribe data update.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LatestUpdateTime"
        "500":
          description: Internal server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /languages:
    get:
      operationId: listLanguages
      responses:
        "200":
          description: Returns the list of languages with available Scribe data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Language"
        "500":
          description: Internal server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /languages/{iso}:
    get:
      operationId: getLanguage
      parameters:
        - name: iso
          in: path
          description: ISO 639 code for the language.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Language was found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Language"
        "400":
          description: Bad parameters passed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Language was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /languages/{iso}/count:
    get:
      operationId: getLanguageDataCount
      parameters:
        - name: iso
          in: path
          description: ISO 639 code for the language.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Language was found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LanguageDataCount"
        "400":
          description: Bad parameters passed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Language was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    LatestUpdateTime:
      type: object
      properties:
        updateTime:
          type: string
    Language:
      type: object
      properties:
        iso:
          type: string
        name:
          type: string
        wikidataId:
          type: string
    LanguageDataCount:
      type: object
      properties:
        totalNouns:
          type: integer
          format: int64
        totalVerbs:
          type: integer
          format: int64
        totalPrepositions:
          type: integer
          format: int64
        translations:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/TranslationsCount"
        totalEmojiKeywords:
          type: integer
          format: int64
    TranslationsCount:
      type: object
      properties:
        iso:
          type: string
        totalTranslations:
          type: integer
          format: int64
