name: pr_ci
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**/*.go"

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: Run PR check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go get .

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          only-new-issues: true

      - name: Run tests and show coverage
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out
